ng_help_desk_homepage:
    path:   /
    defaults: { _controller: NGHelpDeskBundle:Default:index }

login_route:
    path:   /login
    defaults: { _controller: NGHelpDeskBundle:Security:login }

login_check:
    path:   /login_check

incident_my:
    path:   incident
    defaults: { _controller: NGHelpDeskBundle:Incident:incidentMy }

logout:
    path:   /logout