#№ng_help_desk:    resource: @NGHelpDeskBundle/Controller
#    type:     annotation
#

ng_help_desk:
    resource: "@NGHelpDeskBundle/Resources/config/routing.yml"
    prefix:   /

#acme_auth:
#    resource: "@AcmeAuthBundle/Resources/config/routing.yml"
#    prefix:   /sdf

#acme_hello:
#    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation
