security:
    encoders:
        #NG\HelpDeskBundle\Entity\User: 
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
    #    administrators:
    #        entity: { class: NGHelpDeskBundle:User, property: username }
        in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$5quR/MfykVaMaDX8ZeVppuSKPHMf5R5ibUEl3o9r2uK/D0RTQUYKe
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/incident, roles: ROLE_ADMIN }
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }