acme_auth_homepage:
    path:     /asd
    defaults: { _controller: AcmeAuthBundle:Default:login }

acme_auth_success:
    path:     /daslas/success
    defaults: { _controller: AcmeAuthBundle:Success:success }

download:
    path:     /dasdalogin/download
    defaults: { _controller: AcmeAuthBundle:Download:download }
