parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: symfony
    database_user: root
    database_password: '123'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 3ef8ab3937b8a10ac2e98f9c5d73795e3
    database_path: null
